version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=memory
      - MYSQL_USER=memory
      - MYSQL_PASSWORD=memory_pass 
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - MYSQL_DATABASE=memory
      - MYSQL_USER=memory
      - MYSQL_PASSWORD=memory_pass
    ports:
      - "8080:80"
    depends_on:
      - db

  node-api:
    build: ./api
    depends_on:
       - db
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=memory
      - DB_PASS=memory_pass
      - DB_NAME=memory
    links:
      - db:mysql
    ports:
      - "8000:80"

  # client:
  #   tty: true
  #   user: '1000'
  #   build: ./client
  #   volumes:
  #     - ./client:/usr/src/client
  #   ports:
  #     - 80:3000

